on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci:
    strategy:
      matrix:
        include:
          - { os: ubuntu-20.04, ghc: 9.0.1 }
          - { os: macos-11, ghc: 9.0.1 }
          - { os: windows-2019, ghc: 9.0.1 }
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2

      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - run: cabal configure --jobs

      - run: cabal freeze

      - run: cat cabal.project.freeze

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

      - run: cabal build

      - run: cabal check

      - run: mkdir argo-${{ github.sha }}

      - run: mkdir argo-${{ github.sha }}/${{ runner.os }}

      - run: cabal sdist --output-dir argo-${{ github.sha }}/${{ runner.os }}

      - uses: actions/upload-artifact@v2
        with:
          path: argo-${{ github.sha }}
