on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci:
    strategy:
      matrix:
        include:
          - { os: ubuntu-20.04, ghc: 9.0.1 }
          - { os: macos-11, ghc: 9.0.1 }
          - { os: windows-2019, ghc: 9.0.1, ext: .exe }
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2

      - run: mkdir artifact

      - run: mkdir artifact/${{ matrix.os }}

      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - run: cabal configure --enable-benchmarks --enable-tests --flags pedantic --jobs

      - run: cabal freeze

      - run: cat cabal.project.freeze

      - run: cp cabal.project.freeze artifact/${{ matrix.os }}

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-

      - run: cabal install --install-method copy --installdir artifact/${{ matrix.os }}

      - run: cabal test --test-show-details direct

      - run: cabal bench --benchmark-options '--csv artifact/${{ matrix.os }}/benchmark.csv +RTS -T -RTS'

      - run: cabal check

      - run: cabal sdist --output-dir artifact/${{ matrix.os }}

      - uses: svenstaro/upx-action@v2
        with:
          file: artifact/${{ matrix.os }}/argo${{ matrix.ext }}
          args: --best

      - uses: actions/upload-artifact@v2
        with:
          name: argo-${{ github.sha }}
          path: artifact
