name: HLint
on: push
jobs:
  hlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: tfausak/hlint-action@b52248348707a200fd0899897d11430c2d297eaa
        with:
          config: config/hlint.yaml
